/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
const superagent = require("superagent");
const EM = require("./EMTestUtils.js");
jest.setTimeout(60000);




/**
*  This file was automatically generated by EvoMaster on 2026-01-29T12:15:09.630739+07:00[Asia/Ho_Chi_Minh]
*  
*  The generated test suite contains 28 tests
*  
*  Covered targets: 111
*  
*  Used time: 0h 30m 28s
*  
*  Needed budget for current results: 99%
*  
*  This file contains test cases that represent successful calls.
*/

const baseUrlOfSut = "https://test.api.upmount.sotatek.works";


beforeAll( async () => {
});








/**
* Calls:
* (200) GET:/api/countries
*/
test("test_0_GetOnCountriesReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/countries").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("9e1d62e9-6e05-44bc-957c-314c53502b86");
    expect(res_0.body.data.length).toBe(0);
});


/**
* Calls:
* (200) GET:/api/health
*/
test("test_1_GetOnHealthReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/health").set('Accept', "*/*")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("1909f2b3-848c-47d2-b410-c2ddeb1bbaf7");
    expect(res_0.body.data.status).toBe("ok");
    expect(res_0.body.data.uptime).toBe(20554.017359977);
});


/**
* Calls:
* (200) GET:/api/countries
*/
test("test_2_GetOnCountriesReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/countries").set('Accept', "application/json")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("b4f59a94-46f9-471a-a472-748f947b2e95");
    expect(res_0.body.data.length).toBe(0);
});


/**
* Calls:
* (200) GET:/api/health
*/
test("test_3_GetOnHealthReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/health").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("f05c674e-8463-4bf9-a475-95d74f72ea71");
    expect(res_0.body.data.status).toBe("ok");
    expect(res_0.body.data.uptime).toBe(20554.867777342);
});


/**
* Calls:
* (200) GET:/api/health/ready
*/
test("test_4_GetOnReadyReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/health/ready").set('Accept', "*/*")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("f7206231-b157-400e-aaa1-ea2f8bac8a95");
    expect(res_0.body.data.status).toBe("unhealthy");
    expect(res_0.body.data.checks.db.status).toBe("uninitialized");
    expect(res_0.body.data.checks.redis.status).toBe("ok");
    expect(res_0.body.data.checks.kafka.status).toBe("ok");
});


/**
* Calls:
* (200) GET:/api/health/ready
*/
test("test_5_GetOnReadyReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/health/ready").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("cff8cef4-e885-4293-82bc-d676b231abb2");
    expect(res_0.body.data.status).toBe("unhealthy");
    expect(res_0.body.data.checks.db.status).toBe("uninitialized");
    expect(res_0.body.data.checks.redis.status).toBe("ok");
    expect(res_0.body.data.checks.kafka.status).toBe("ok");
});


/**
* Calls:
* (204) OPTIONS:/api/processing/{path}
*/
test("test_6_OptionsOnProcessReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/processing/zN8hLZZ").set('Accept', "*/*")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/processing/{path}
*/
test("test_7_OptionsOnProcessReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/processing/wB").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (200) GET:/api/users/rbac/roles
*/
test("test_8_GetOnRolesReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/users/rbac/roles").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("8866c617-b98b-4726-8df5-03cbf730247e");
    expect(res_0.body.data.length).toBe(3);
    expect(res_0.body.data[0].name).toBe("organization_owner");
    expect(res_0.body.data[0].displayName).toBe("Owner");
    expect(res_0.body.data[1].name).toBe("organization_writer");
    expect(res_0.body.data[1].displayName).toBe("Writer");
    expect(res_0.body.data[2].name).toBe("organization_reader");
    expect(res_0.body.data[2].displayName).toBe("Reader");
});


/**
* Calls:
* (200) GET:/api/users/organization-kyb/primary-owner-data
*/
test("test_9_GetOnPrimary_owner_dataReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/users/organization-kyb/primary-owner-data").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("f58546d7-aec5-4851-8374-ce91eb322a85");
    expect(res_0.body.data.fullName).toBe("John Mock-Doe");
    expect(res_0.body.data.email).toBe("trung.hoang+testuser@sotatek.com");
    expect(res_0.body.data.country).toBe(null);
    expect(res_0.body.data.dateOfBirth).toBe("2004-02-01");
});


/**
* Calls:
* (200) GET:/api/users/profile/me
*/
test("test_10_GetOnMeReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/users/profile/me").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("246a647e-e0e1-43e5-83b9-c5577c77fc1a");
    expect(res_0.body.data.email).toBe("trung.hoang+testuser@sotatek.com");
    expect(res_0.body.data.displayName).toBe("John Doe");
    expect(res_0.body.data.roleInfo.role).toBe("user");
    expect(Object.keys(res_0.body.data.permissionsInfo).length).toBe(0);
    expect(res_0.body.data.imageUrl).toBe("https://example.com/image.jpg");
    expect(res_0.body.data.hasPassword).toBe(true);
});


/**
* Calls:
* (201) POST:/api/users/profile/me
* Using 2 examples:
*   (-) BODY -> John Doe
*   (-) BODY -> https://example.com/image.jpg
*/
test("test_11_PostOnMeReturns201", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/users/profile/me").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"displayName\": \"John Doe\", " + 
                " \"imageUrl\": \"https://example.com/image.jpg\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(201);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("27ab617f-caae-4f98-9bb2-223f69bea4f1");
    expect(Object.keys(res_0.body.data).length).toBe(0);
});


/**
* Calls:
* (201) POST:/api/users/auth/logout
*/
test("test_12_PostOnLogoutReturns201", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/users/auth/logout").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"EbQb\": \"X\", " + 
                " \"0dbR\": \"cGYlNaxs\", " + 
                " \"\": \"QL3VOMw\", " + 
                " \"okT5Xz9zPHHY6_\": \"AWzcyTE5LwmKeT\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(201);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("1d3f876f-ade9-4823-b66d-6500c8297000");
    expect(Object.keys(res_0.body.data).length).toBe(0);
});


/**
* Calls:
* (201) POST:/api/users/auth/forgot-password
* Using 1 example:
*   (-) BODY -> user@example.com
*/
test("test_13_PostOnForgot_passwordReturns201", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/users/auth/forgot-password").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"email\": \"user@example.com\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(201);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("df24deec-8b86-4ee7-9f70-298f86540e5d");
    expect(res_0.body.data.otpSentBefore).toBe(true);
    expect(res_0.body.data.nextResendOtpAt).toBe(1.769663746741E12);
});


/**
* Calls:
* (201) POST:/api/users/auth/register
* Using 2 examples:
*   (-) BODY -> Test123!
*   (-) BODY -> user@example.com
*/
test("test_14_PostOnRegisterReturns201", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/users/auth/register").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"email\": \"user@example.com\", " + 
                " \"password\": \"Test123!\", " + 
                " \"displayName\": \"Z\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(201);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("7dec93bb-851e-476d-a413-73cf6b2f1ebc");
    expect(res_0.body.data.nextResendOtpAt).toBe(1.769663699676E12);
    expect(res_0.body.data.otpSentBefore).toBe(true);
    expect(res_0.body.data.timeExp).toBe(900000.0);
});


/**
* Calls:
* (201) POST:/api/users/auth/register
* Using 2 examples:
*   (-) BODY -> Test123!
*   (-) BODY -> user@example.com
*/
test("test_15_PostOnRegisterReturns201", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/users/auth/register").set('Accept', "application/json")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"email\": \"user@example.com\", " + 
                " \"password\": \"Test123!\", " + 
                " \"displayName\": \"Owner\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(201);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("701cc80b-3d00-4d1f-967f-76807924d88c");
    expect(res_0.body.data.nextResendOtpAt).toBe(1.769663765975E12);
    expect(res_0.body.data.otpSentBefore).toBe(false);
    expect(res_0.body.data.timeExp).toBe(900000.0);
});


/**
* Calls:
* (201) POST:/api/users/auth/forgot-password
*/
test("test_16_PostOnForgot_passwordReturns201", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/users/auth/forgot-password").set('Accept', "application/json")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"email\": \"trung.hoang+testuser@sotatek.com\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(201);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("d768c9f8-e6ef-4067-a25c-1243abe00f41");
    expect(res_0.body.data.otpSentBefore).toBe(true);
    expect(res_0.body.data.nextResendOtpAt).toBe(1.769663768504E12);
});


/**
* Calls:
* (204) OPTIONS:/api/processing/users/{path}
*/
test("test_17_OptionsOnUserReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/processing/users/gP9PozGswMZ2").set('Accept', "*/*")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/monitoring/users/{path}
*/
test("test_18_OptionsOnUserReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/monitoring/users/_k6us5k").set('Accept', "*/*")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/processing/users/{path}
*/
test("test_19_OptionsOnUserReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/processing/users/AKtxuTCEuHO4v3Zl").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (204) OPTIONS:/api/monitoring/users/{path}
*/
test("test_20_OptionsOnUserReturns204", async () => {
    
    const res_0 = await superagent
            .options(baseUrlOfSut + "/api/monitoring/users/x").set('Accept', "*/*")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(204);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (302) GET:/api/users/auth/google
*/
test("test_21_GetOnGoogleReturns302", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/users/auth/google").set('Accept', "*/*")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(302);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});


/**
* Calls:
* (200) GET:/api/users/vault-accounts/{id}/users
*/
test("test_22_GetOnUsersReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/users/vault-accounts/H6Imp5CeVCC/users?" + 
                "limit=10&" + 
                "sortDirection=ASC&" + 
                "keyword=H8n_1bK_nZgD6").set('Accept', "*/*")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("6fb59db9-a823-49e7-ae2f-3b50435f1793");
    expect(res_0.body.data.length).toBe(0);
    expect(res_0.body.meta.totalItems).toBe(0.0);
    expect(res_0.body.meta.itemCount).toBe(0.0);
    expect(res_0.body.meta.itemsPerPage).toBe(10.0);
    expect(res_0.body.meta.totalPages).toBe(0.0);
    expect(res_0.body.meta.currentPage).toBe(1.0);
});


/**
* Calls:
* (200) GET:/api/users/vault-accounts/{id}/users
*/
test("test_23_GetOnUsersReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/users/vault-accounts/9L/users?" + 
                "sortDirection=DESC&" + 
                "keyword=CLw3").set('Accept', "*/*")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("5e8be2be-0cb2-4bd3-ab5c-b681b1993a2f");
    expect(res_0.body.data.length).toBe(0);
    expect(res_0.body.meta.totalItems).toBe(0.0);
    expect(res_0.body.meta.itemCount).toBe(0.0);
    expect(res_0.body.meta.itemsPerPage).toBe(10.0);
    expect(res_0.body.meta.totalPages).toBe(0.0);
    expect(res_0.body.meta.currentPage).toBe(1.0);
});


/**
* Calls:
* (200) GET:/api/users/vault-accounts/{id}/users
*/
test("test_24_GetOnUsersReturnsObject", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/users/vault-accounts/8i_IJ0Ao/users?" + 
                "sortBy=cE3Sn&" + 
                "keyword=eKzbtU6ADg").set('Accept', "*/*")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(200);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("9345230c-ae8e-4745-96b4-09f671d11fb1");
    expect(res_0.body.data.length).toBe(0);
    expect(res_0.body.meta.totalItems).toBe(0.0);
    expect(res_0.body.meta.itemCount).toBe(0.0);
    expect(res_0.body.meta.itemsPerPage).toBe(10.0);
    expect(res_0.body.meta.totalPages).toBe(0.0);
    expect(res_0.body.meta.currentPage).toBe(1.0);
});


/**
* Calls:
* (201) POST:/api/users/auth/verify-email/resend
* Using 1 example:
*   (-) BODY -> user@example.com
*/
test("test_25_PostOnResendReturns201", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/users/auth/verify-email/resend").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"email\": \"user@example.com\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(201);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("7fcc4fd6-d6df-472e-87c7-61c54be45ff7");
    expect(res_0.body.data.nextResendOtpAt).toBe(1.769663699676E12);
    expect(res_0.body.data.otpSentBefore).toBe(true);
});


/**
* Calls:
* (201) POST:/api/users/auth/verify-email/resend
* Using 1 example:
*   (-) BODY -> user@example.com
*/
test("test_26_PostOnResendReturns201", async () => {
    
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/users/auth/verify-email/resend").set('Accept', "application/json")
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"email\": \"user@example.com\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(201);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.errorCode).toBe("0");
    expect(res_0.body.message).toBe("success");
    expect(res_0.body.requestId).toBe("7c636e1c-fe02-421e-bea9-310ae1bf9a79");
    expect(res_0.body.data.nextResendOtpAt).toBe(1.769663765975E12);
    expect(res_0.body.data.otpSentBefore).toBe(true);
});


/**
* Calls:
* (302) GET:/api/users/auth/google/callback
*/
test("test_27_GetOnCallbackReturns302", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/users/auth/google/callback").set('Accept', "*/*")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(302);
    expect(res_0.body===null || res_0.body===undefined || res_0.body==="" || Object.keys(res_0.body).length === 0).toBe(true);
});
