/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
const superagent = require("superagent");
const EM = require("./EMTestUtils.js");
jest.setTimeout(60000);




/**
*  This file was automatically generated by EvoMaster on 2026-01-29T12:15:09.607581+07:00[Asia/Ho_Chi_Minh]
*  
*  The generated test suite contains 7 tests
*  
*  Covered targets: 66
*  
*  Used time: 0h 30m 28s
*  
*  Needed budget for current results: 99%
*  
*  This file contains test cases that are likely to indicate faults.
*/

const baseUrlOfSut = "https://test.api.upmount.sotatek.works";


beforeAll( async () => {
});








/**
* Calls:
* (500) POST:/api/users/organization-kyb
* Found 1 potential fault of type-code 100
* Using 7 examples:
*   (-) BODY -> 1
*   (-) BODY -> 1990-01-01
*   (-) BODY -> 2010-05-20
*   (-) BODY -> Director
*   (-) BODY -> Hieu Nguyen
*   (-) BODY -> Legal Business Name
*   (-) BODY -> TAX-987654
*/
test("test_0_PostOnOrganization_kybCauses500_internalservererror", async () => {
    
    // Fault100. HTTP Status 500. null.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/users/organization-kyb").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"legalBusinessName\": \"Legal Business Name\", " + 
                " \"businessType\": \"partnership\", " + 
                " \"countryId\": 1, " + 
                " \"contractEmail\": \"trung.hoang+testuser@sotatek.com\", " + 
                " \"businessAddress\": \"_hgMgWw9jvC\", " + 
                " \"businessDescription\": \"Svelwi8\", " + 
                " \"websiteUrl\": \"sRfeAlbOW2llvhI\", " + 
                " \"registrationNumber\": \"XVSOK67DQB2lig\", " + 
                " \"dateOfIncorporation\": \"2010-05-20\", " + 
                " \"taxId\": \"TAX-987654\", " + 
                " \"ownerships\": [ " + 
                " { " + 
                " \"fullName\": \"Hieu Nguyen\", " + 
                " \"dateOfBirth\": \"1990-01-01\", " + 
                " \"countryId\": 0.8857014482249628, " + 
                " \"email\": \"Lf2t\", " + 
                " \"ownerRole\": \"primary_owner\", " + 
                " \"organizationRole\": \"Zp1Tv5fHl\" " + 
                " }, " + 
                " { " + 
                " \"fullName\": \"John Mock-Doe\", " + 
                " \"dateOfBirth\": \"2004-02-01\", " + 
                " \"countryId\": 0.2953792864053121, " + 
                " \"email\": \"trung.hoang+testuser@sotatek.com\", " + 
                " \"ownerRole\": \"beneficial_owner\", " + 
                " \"organizationRole\": \"Director\" " + 
                " } " + 
                " ], " + 
                " \"fileIds\": [] " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(500);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.statusCode).toBe(500.0);
    expect(res_0.body.requestId).toBe("78a6f789-abee-4105-8fa8-ab50e47f722a");
    expect(res_0.body.error.code).toBe("000001");
    expect(res_0.body.error.message).toBe("column OrganizationKybEntity.contract_email does not exist");
});


/**
* Calls:
* (500) POST:/api/users/organization-kyb
* Found 1 potential fault of type-code 100
* Using 6 examples:
*   (-) BODY -> 1
*   (-) BODY -> 1990-01-01
*   (-) BODY -> 2010-05-20
*   (-) BODY -> Hieu Nguyen
*   (-) BODY -> REG-123456
*   (-) BODY -> owner@example.com
*/
test("test_1_PostOnOrganization_kybCauses500_internalservererror", async () => {
    
    // Fault100. HTTP Status 500. null.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/users/organization-kyb").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"legalBusinessName\": \"eMBMCk\", " + 
                " \"businessType\": \"other\", " + 
                " \"countryId\": 0.7252995711478598, " + 
                " \"contractEmail\": \"trung.hoang+testuser@sotatek.com\", " + 
                " \"businessAddress\": \"utgEzO3ZKOC1\", " + 
                " \"businessDescription\": \"v9Ml6iUJz2AXlSA4\", " + 
                " \"registrationNumber\": \"REG-123456\", " + 
                " \"dateOfIncorporation\": \"2010-05-20\", " + 
                " \"ownerships\": [ " + 
                " { " + 
                " \"fullName\": \"Hieu Nguyen\", " + 
                " \"dateOfBirth\": \"1990-01-01\", " + 
                " \"countryId\": 1, " + 
                " \"email\": \"tVH1svXGiiQJjYP\", " + 
                " \"ownerRole\": \"primary_owner\", " + 
                " \"organizationRole\": \"xBi\" " + 
                " }, " + 
                " { " + 
                " \"fullName\": \"John Mock-Doe\", " + 
                " \"dateOfBirth\": \"1990-01-01\", " + 
                " \"countryId\": 0.7477451057450782, " + 
                " \"email\": \"owner@example.com\", " + 
                " \"ownerRole\": \"primary_owner\", " + 
                " \"organizationRole\": \"vBGjZQFA7Sy\" " + 
                " } " + 
                " ], " + 
                " \"fileIds\": [ " + 
                " \"s6rkid26mvP\", " + 
                " \"0FELgW25WIR\" " + 
                " ] " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(500);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.statusCode).toBe(500.0);
    expect(res_0.body.requestId).toBe("e211fdd8-0e1d-4d15-aea3-e6292f39af5a");
    expect(res_0.body.error.code).toBe("000001");
    expect(res_0.body.error.message).toBe("column OrganizationKybEntity.contract_email does not exist");
});


/**
* Calls:
* (500) GET:/api/users/organization-kyb/kyb-status
* Found 1 potential fault of type-code 100
*/
test("test_2_GetOnKyb_statusCauses500_internalservererror", async () => {
    
    // Fault100. HTTP Status 500. null.
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/users/organization-kyb/kyb-status").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(500);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.statusCode).toBe(500.0);
    expect(res_0.body.requestId).toBe("3cdab51c-15c0-49fb-91d7-67c84212288e");
    expect(res_0.body.error.code).toBe("000001");
    expect(res_0.body.error.message).toBe("column OrganizationKybEntity.contract_email does not exist");
});


/**
* Calls:
* (500) POST:/api/users/files/upload-image
* Found 1 potential fault of type-code 100
*/
test("test_3_PostOnUpload_imageCauses500_internalservererror", async () => {
    
    // Fault100. HTTP Status 500. null.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/users/files/upload-image").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .set('Content-Type','application/x-www-form-urlencoded')
            .send("image=BiV5ahyBG4")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(500);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.statusCode).toBe(500.0);
    expect(res_0.body.requestId).toBe("26e7b8c3-7546-447c-972b-dfaf77920fde");
    expect(res_0.body.error.code).toBe("000001");
    expect(res_0.body.error.message).toBe("Cannot read properties of undefined (reading 'originalname')");
});


/**
* Calls:
* 1 - (403) GET:/api/users/vault-accounts/{id}/users
* 2 - (200) GET:/api/users/vault-accounts/{id}/users
* 3 - (401) POST:/api/users/auth/refresh-token
* Found 1 potential fault of type-code 205
* Using 1 example:
*   (-) BODY -> eyJhbGci...
*/
test("test_4_PostOnRefresh_tokenAuthenticatedbutwronglytoldnot", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/users/vault-accounts/10015/users?page=1").set('Accept', "*/*")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.statusCode).toBe(403.0);
    expect(res_0.body.requestId).toBe("6a1ce5f5-5a00-4415-9b08-32aa83a5ddd6");
    expect(res_0.body.error.code).toBe("000001");
    expect(res_0.body.error.message).toBe("{\"statusCode\":403,\"success\":false,\"message\":\"Insufficient permissions\",\"data\":null,\"errorCode\":\"INTERNAL_SERVER_ERROR\",\"requestId\":\"70357bda-1bf2-4306-a5d4-5f53869696b7\",\"timestamp\":\"2026-01-29T05:15:09.293Z\"}");
    
    const res_1 = await superagent
            .get(baseUrlOfSut + "/api/users/vault-accounts/H6Imp5CeVCC/users?" + 
                "limit=10&" + 
                "sortDirection=ASC&" + 
                "keyword=H8n_1bK_nZgD6").set('Accept', "*/*")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_1.status).toBe(200);
    expect(res_1.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_1.body.errorCode).toBe("0");
    expect(res_1.body.message).toBe("success");
    expect(res_1.body.requestId).toBe("fe697338-e6d0-47ed-94e7-0f72aff61f0e");
    expect(res_1.body.data.length).toBe(0);
    expect(res_1.body.meta.totalItems).toBe(0.0);
    expect(res_1.body.meta.itemCount).toBe(0.0);
    expect(res_1.body.meta.itemsPerPage).toBe(10.0);
    expect(res_1.body.meta.totalPages).toBe(0.0);
    expect(res_1.body.meta.currentPage).toBe(1.0);
    
    // Fault205. Wrongly Not Recognized as Authenticated. null.
    const res_2 = await superagent
            .post(baseUrlOfSut + "/api/users/auth/refresh-token").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"refreshToken\": \"eyJhbGci...\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_2.status).toBe(401);
    expect(res_2.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_2.body.success).toBe(false);
    expect(res_2.body.statusCode).toBe(401.0);
    expect(res_2.body.requestId).toBe("af7aa12c-e139-4f7c-8b32-63e74c61fde7");
    expect(res_2.body.error.code).toBe("000001");
    expect(res_2.body.error.message).toBe("Unauthorized");
});


/**
* Calls:
* (500) POST:/api/users/auth/google/token
* Found 1 potential fault of type-code 100
* Using 1 example:
*   (-) BODY -> eyJhbGci...
*/
test("test_5_PostOnTokenCauses500_internalservererror", async () => {
    
    // Fault100. HTTP Status 500. null.
    const res_0 = await superagent
            .post(baseUrlOfSut + "/api/users/auth/google/token").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .set('Content-Type','application/json')
            .send(" { " + 
                " \"idToken\": \"eyJhbGci...\" " + 
                " } ")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(500);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.statusCode).toBe(500.0);
    expect(res_0.body.requestId).toBe("f4db2140-7e81-494d-a5d2-607c80e22d8f");
    expect(res_0.body.error.code).toBe("000001");
    expect(res_0.body.error.message).toBe("Wrong number of segments in token: eyJhbGci...");
});


/**
* Calls:
* 1 - (403) GET:/api/users/vault-accounts/{id}/users
* 2 - (200) GET:/api/users/vault-accounts/{id}/users
* 3 - (401) POST:/api/users/identity-verification/kyc/webhook
* Found 1 potential fault of type-code 205
*/
test("test_6_PostOnWebhookAuthenticatedbutwronglytoldnot", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/users/vault-accounts/10015/users?page=1").set('Accept', "*/*")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_0.status).toBe(403);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.body.success).toBe(false);
    expect(res_0.body.statusCode).toBe(403.0);
    expect(res_0.body.requestId).toBe("6182372b-1361-4b72-970c-642ad00b8366");
    expect(res_0.body.error.code).toBe("000001");
    expect(res_0.body.error.message).toBe("{\"statusCode\":403,\"success\":false,\"message\":\"Insufficient permissions\",\"data\":null,\"errorCode\":\"INTERNAL_SERVER_ERROR\",\"requestId\":\"33078237-c108-4b3d-a0ec-2ff2ef3d1935\",\"timestamp\":\"2026-01-29T05:15:09.405Z\"}");
    
    const res_1 = await superagent
            .get(baseUrlOfSut + "/api/users/vault-accounts/H6Imp5CeVCC/users?" + 
                "limit=10&" + 
                "sortDirection=ASC&" + 
                "keyword=H8n_1bK_nZgD6").set('Accept', "*/*")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_1.status).toBe(200);
    expect(res_1.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_1.body.errorCode).toBe("0");
    expect(res_1.body.message).toBe("success");
    expect(res_1.body.requestId).toBe("3ef80758-a802-43a2-9c99-b29a8403883f");
    expect(res_1.body.data.length).toBe(0);
    expect(res_1.body.meta.totalItems).toBe(0.0);
    expect(res_1.body.meta.itemCount).toBe(0.0);
    expect(res_1.body.meta.itemsPerPage).toBe(10.0);
    expect(res_1.body.meta.totalPages).toBe(0.0);
    expect(res_1.body.meta.currentPage).toBe(1.0);
    
    // Fault205. Wrongly Not Recognized as Authenticated. null.
    const res_2 = await superagent
            .post(baseUrlOfSut + "/api/users/identity-verification/kyc/webhook").set('Accept', "application/json")
            .set("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDAxNSIsImVtYWlsIjoidHJ1bmcuaG9hbmcrdGVzdHVzZXJAc290YXRlay5jb20iLCJyb2xlIjoidXNlciIsIm9yZ2FuaXphdGlvbklkIjpudWxsLCJvcmdhbml6YXRpb25Pd25lciI6ZmFsc2UsImtleVRva2VuIjoiNDAwYmI2ODQtOWFmNi00MjkwLTg0ZTEtMDI0MTBlZTNiNDMyIiwidHlwIjoiQUNDRVNTIiwiaWF0IjoxNzY5NjU5NjI3LCJleHAiOjE3Njk3NDYwMjd9.T8zaY4iVD-0MAGYD4IPavzSw3yZrhcbd6iHyaUKEUTA") // Fixed Headers
            .ok(res => res.status);
    
    expect(res_2.status).toBe(401);
    expect(res_2.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_2.body.success).toBe(false);
    expect(res_2.body.statusCode).toBe(401.0);
    expect(res_2.body.requestId).toBe("a3f9d50b-8b6e-4734-a723-ff3c2500d1a2");
    expect(res_2.body.error.code).toBe("000001");
    expect(res_2.body.error.message).toBe("Unsupported algorithm: undefined");
});
